version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server:/app
      - /app/node_modules    
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: npm run dev -- --host

volumes:
  redis-data: